### ISSUE TITLE
Train data 

### ISSUE THREAD

**Issue by ihameed11** [MIDASverse/MIDASpy#13]
when i try to train data " adult data" 
this message showed up 
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Imputation target contains no missing values. Please ensure missing values are encoded as type np.nan
I tried to replace the missing values with np.nan but same message came

**Comment by ranjitlall** [comment]
Hi @ihameed11, so we can troubleshoot this could you provide us with the following:

Operating system
Python, numpy, and tensorflow versions
A minimum working example that raises this error
Thanks!

**Comment by tsrobinson** [comment]
I'm closing this issue since it is the same as MIDASverse/rMIDAS#14 -- if you are encountering this issue directly in MIDASpy rather than via rMIDAS please re-open this issue and I'll close the other one.
