### ISSUE TITLE
module 'MIDASpy' has no attribute 'cat_conv'

### ISSUE THREAD

**Issue by ihameed11** [MIDASverse/MIDASpy#14]
AttributeError: module 'MIDASpy' has no attribute 'cat_conv'

how i can solve this problem ?  I'm using jupyter

**Comment by ihameed11** [comment]
operating system: windows 10 64bit
python 3.9.4
numpy  1.19.5
tensorflow 2.5.0rc2
example: I was trying the same example midas_demo

**Comment by tsrobinson** [comment]
Hi @ihameed11, given the error message, it seems you may not have the latest version of MIDASpy -- `cat_conv()` was introduced in v.1.2.1.

I've just run the MIDASpy example using your spec and don't encounter the same error (with and without using jupyter).

Please try upgrading MIDASpy by running `pip install --upgrade midaspy` at the command line and see if that fixes the issue.

**Comment by ihameed11** [comment]
@tsrobinson  yes now it's working thank you 
but what about this code :
for i in imputations:
 file_out = ``midas_imp_" + str(n) + ``.csv"
 i.to_csv(file_out, index=False)
 n += 1
 
 I'm getting   :     file_out = ``midas_imp_" + str(n) + ``.csv"
               ^
SyntaxError: invalid syntax

**Comment by tsrobinson** [comment]
Thanks for spotting this -- the opening quotation marks were incorrect in the example. I've updated the code 5b32c361dd11a813c62adadf334c617cfe332403, but for reference it should read:
``` 
for i in imputations:
   file_out = "midas_imp_" + str(n) + ".csv"
   i.to_csv(file_out, index=False)
   n += 1
```

**Comment by ihameed11** [comment]
@tsrobinson  thank you

**Comment by catubc** [comment]
Yes, I also had this issue, had to uninstall everything via pip and reinstall as the update was not going through. Tx
