### ISSUE TITLE
How to reverse One hot encoding

### ISSUE THREAD

**Issue by khanwa** [MIDASverse/MIDASpy#16]
Hello,

How to get the data in the original form (reverse dummies). We receive the imputed dataset in one hot encoded form. But how to convert it into the original dataset (the categorical data).
Thank you

**Comment by tsrobinson** [comment]
Hi @khanwa,thanks for raising this issue! 

I have now updated [the example notebook](https://github.com/MIDASverse/MIDASpy/Examples/midas_demo.ipynb) to demonstrate how the imputed one hot data can be transformed back into categorical variables. I hope that helps, but do feel free to reopen this issue if not.

Tom
