### ISSUE TITLE
Heuristics on choosing a model structure

### ISSUE THREAD

**Issue by AnotherSamWilson** [MIDASverse/MIDASpy#28]
Hi,

I was wondering if there was any heuristics on choosing a model structure for different types / sizes of datasets. For instance, if I had a standard corporate dataset with 20,000 rows and 15 columns, are there any sure-fire methods / parameters I should be using? Are there any clear do's or dont's in certain situations?

**Comment by ranjitlall** [comment]
Hi @AnotherSamWilson, thanks for your question. We think the default settings should be fine for your dataset, but we've actually been working on a paper that discusses various heuristics/diagnostics for choosing model parameters. We'd be happy to share it, if you give us your email address (mine is R.Lall@lse.ac.uk).
