### ISSUE TITLE
Support for python 3.10?

### ISSUE THREAD

**Issue by zhimin-z** [MIDASverse/MIDASpy#30]
I see the post [enquiring about support for 3.9](https://github.com/MIDASverse/MIDASpy/issues/15) two years ago, but how about 3.10?

**Comment by ranjitlall** [comment]
Hi @zhimin-z, this should be coming within the next few weeks (we're working on an update now).

**Comment by edvinskis** [comment]
Hi @zhimin-z, Python 3.10 is now supported in the newest release (v1.2.4). Please don't hesitate to reach out if you have any more questions. I'll be closing this issue.
