### ISSUE TITLE
TensorFlow 2 compatibility

### ISSUE THREAD

**Issue by harrietdrage** [MIDASverse/MIDASpy#39]
New to python but very interested in testing MIDASpy with fossil data. However, I'm not able to get round the issue of incompatibility with TensorFlow 2: 
raise tfVersionError("midas v1.0 is currently only compatible with TensorFlow 1.X") 

Are there any current ways round this/will it be fixed in future?

Thanks!

**Comment by tsrobinson** [comment]
Hi, sorry for the slow reply! 

I think you may have an older version of MIDASpy installed. I'd recommend running `pip install --upgrade MIDASpy` and see if that resolves the issue. If not, feel free to share a bit more info about your environment (Python version, OS etc.) and I'll try look into it further. Thanks!

**Comment by harrietdrage** [comment]
Hello, thanks for your response!

Just to say that the issue wasn't actually any of the versions, it seems that the problem was with running this in Python 3.12. On trying using Anaconda and a virtual environment running Python 3.10.x everything worked fine!
Now to get on to running with my own data. Thanks :)

**Comment by tsrobinson** [comment]
Ah, thanks for letting us know! We'll try add a guard rail to prevent this in future.
